version: '3.1'

services:

  db-server:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: test

  app-server:
    image: node:8.12-alpine
    restart: always
    command: sh /usr/src/app/server/start.sh
    ports:
      - 8001:8080
    volumes:
      - ./:/usr/src/app
    environment:
      - MYSQL_USER=root
      - MYSQL_HOST=db-server
      - MYSQL_PASSWORD=test
    links:
      - db-server
